### ISSUE TITLE
neco.hpp:3:10: fatal error: SFML/Graphics.hpp: No such file or directory

### ISSUE THREAD

**Issue by fily-gif** [adenosinetp10/Neco-Arc-DVDLogo#1]
Heya! I am trying to compile this repository for Fedora 38 with kde plasma, but I get an error:

`[fily@hp Neco-Arc-DVDLogo]$ make
g++ -std=c++17 -c main.cpp
In file included from main.cpp:1:
neco.hpp:3:10: fatal error: SFML/Graphics.hpp: No such file or directory
    3 | #include <SFML/Graphics.hpp>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [makefile:11: main.o] Error 1`

I have installed SFML package and it still gave me this error.

**Comment by fily-gif** [comment]
I have ran just `make` btw, the full formatted "log" is:

```
[fily@hp Neco-Arc-DVDLogo]$ make
g++ -std=c++17 -c main.cpp
In file included from main.cpp:1:
neco.hpp:3:10: fatal error: SFML/Graphics.hpp: No such file or directory
    3 | #include <SFML/Graphics.hpp>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [makefile:11: main.o] Error 1```

**Comment by advnpzn** [comment]
Hi @fily-gif ,

Have you tried installing SFML before running `make` ?
```
dnf install SFML SFML-devel
```

**Comment by fily-gif** [comment]
have installed SFML, but not SFML-devel. Fixed, thanks! (burunyuu)
